### ISSUE TITLE
Complexity for interval scheduling

### ISSUE THREAD

**Issue by tabakg** [vsoch/algorithms#2]
The current complexity is O(n^2) because whenever we are looking for overlaps against a given task we check against all remaining tasks. By keeping track of the chronological order of when the tasks start, we can ensure overlapping tasks with the task that ends soonest always come first. This way we don't have to check all tasks for overlaps, but instead iterate until either there are no more tasks or the next task doesn't overlap (since none of the following tasks would overlap either). This reduces the runtime complexity to O(n logn) because of the required sorting steps.

**Comment by vsoch** [comment]
yes makes sense! Let me see if I can open a PR to suggest changes for discussion.
